from fastapi import APIRouter, Query
from datetime import datetime, timezone
from typing import Optional
import uuid

from app.models.event import SecurityEvent
from app.services.event_service import (
    create_event,
    get_events,
    get_events_by_camera,
)


router = APIRouter(
    prefix="/api/events",
    tags=["Events"]
)


@router.get("/")
async def list_events(
    camera_id: Optional[str] = Query(None)
):
    if camera_id:
        events = get_events_by_camera(camera_id)
    else:
        events = get_events()

    return {
        "status": "success",
        "count": len(events),
        "events": [
            event.model_dump(mode="json")
            for event in events
        ]
    }


@router.post("/test")
async def create_test_event():
    event = SecurityEvent(
        event_id=str(uuid.uuid4()),
        event_type="test_alert",
        severity="low",
        camera_id="CAM-001",
        location="Ahmedabad Traffic Junction",
        timestamp=datetime.now(timezone.utc),
        description="Test event generated by Sentinel VisionGuard",
        metadata={
            "source": "test_api"
        }
    )

    create_event(event)

    return {
        "status": "created",
        "event": event.model_dump(mode="json")
    }
